name: .NET Core

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
        dotnetcore:
          - 2.2.207

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnetcore }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  release:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207

      - name: Install Dependencies
        run: npm install
      - name: Pack
        run: npm run pack
      # - name: Publish
      #   run: npm run publish
